<?php
// $Id$

/**
 * Implementation of hook_help
 */
function image_help($section) {
  switch ($section) {
    case 'admin/help#image':
      $output = '<p>'. t('The image module is used to create and administer images for your site. Each image is stored as a post, with thumbnails of the original generated automatically. There are two default thumbnail sizes, thumbnail and preview. The thumbnail size is shown as the preview for image posts and when browsing image galleries. The preview is the default size when first displaying an image node.') .'</p>';
      $output .= '<p>' .t('Image administration allows the image directory and the image sizes to be set.</p><p>
Image galleries are used to organize and display images in galleries.   The list tab allows users to edit existing image gallery names, descriptions, parents and relative position, known as a weight.  The add galleries tab allows you to create a new image gallery defining name, description, parent and weight.') .'</p>';
      $output .= t('<p>You can</p>
<ul>
<li>view image handling messages in <a href="%admin-settings">administer &gt;&gt; settings</a>.</li>
<li>view lists and add image galleries at <a href="%admin-image-galleries" >administer &gt;&gt; image galleries.</a></li>
<li>configure image sizes and file directories at <a href="%admin-settings-image">administer &gt;&gt; settings &gt;&gt; image</a>.</li>
<li>use the <a href="%external-http-drupal-org-project-img_assist">image assist module</a> to upload and insert images into posts.</li>
', array('%admin-settings' => url('admin/settings'), '%admin-image-galleries' => url('admin/image/galleries'), '%admin-settings-image' => url('admin/settings/image'), '%external-http-drupal-org-project-img_assist' => 'http://drupal.org/project/img_assist')) .'</ul>';
      $output .= '<p>'. t('For more information please read the configuration and customization handbook <a href="%image">Image page</a>.', array('%image' => 'http://www.drupal.org/handbook/modules/image/')) .'</p>';
      return $output;
    case 'admin/modules#description':
      return t('Allows uploading of images and creating image galleries.');
    case 'node/add#image':
      return t('An image (with thumbnail). This is ideal for publishing photographs or screenshots.');
    case 'admin/image':
      return t('Image galleries can be used to organize and present groups of images. Galleries may be nested. To add a new gallery click the "add gallery" tab.');
  }
}

/**
 * Implementation of hook_node_info
 */
function image_node_info() {
  return array('image' => array('name' => t('image'), 'base' => 'image'));
}

/**
 * Implementation of hook_perm
 */
function image_perm() {
  return array('administer images', 'create images');
}

/**
 * Implementation of hook_access
 */
function image_access($op, $node) {
  global $user;

  if ($op == 'create' && user_access('create images')) {
    return TRUE;
  }

  if ($op == 'update' && $user->uid == $node->uid) {
    return TRUE;
  }

  if ($op == 'delete' && $user->uid == $node->uid) {
    return TRUE;
  }
}

/**
 * Implementation of hook_settings
 */
function image_settings() {
  _image_check_settings();

  $form['image_updated'] = array('#type' => 'hidden', '#value' => time());

  $form['paths'] = array('#type' => 'fieldset', '#title' => t('File paths'));
  $form['paths']['image_default_path'] = array('#type' => 'textfield', '#title' => t('Default image path'), '#default_value' => variable_get('image_default_path', 'images'), '#description' => t('Subdirectory in the directory "%dir" where pictures will be stored. Do not include trailing slash.', array('%dir' => theme('placeholder', variable_get('file_directory_path', 'files')))));

  $form['sizes'] = array('#type' => 'fieldset', '#title' => t('Image sizes'));
  $form['sizes']['image_sizes'] = image_settings_sizes_form();

  $form['gallery'] = array('#type' => 'fieldset', '#title' => t('Gallery settings'));
  $form['gallery']['image_images_per_page'] = array('#type' => 'textfield', '#title' => t('Images per page'), '#default_value' => variable_get('image_images_per_page', 6), '#size' => 3, '#description' => t('Sets the number of images to be displayed in a gallery page.'));

  return $form;
}

function image_settings_sizes_form() {
  $sizes = _image_get_sizes();

  $form['#type'] = 'item';
  $form['#description'] = t('Select various pixel dimensions, "thumbnail" and "preview" are required.');
  $form['#tree'] = TRUE;
  $form['#theme'] = 'image_settings_sizes_form';
  for ($i = 0; $i < 5; $i++) {
    $form[$i]['label'] = array('#type' => 'textfield', '#default_value' => $sizes[$i]['label'], '#size' => 25);
    if (in_array($sizes[$i]['label'], _image_required_sizes())) {
      $form[$i]['label']['#attributes'] = array('disabled' => 'disabled');
      $form[$i]['label']['#value'] = $sizes[$i]['label'];
    }
    $form[$i]['width'] = array('#type' => 'textfield', '#default_value' => $sizes[$i]['width'], '#size' => 5, '#maxlength' => 5);
    $form[$i]['height'] = array('#type' => 'textfield', '#default_value' => $sizes[$i]['height'], '#size' => 5, '#maxlength' => 5);
  }

  return $form;
}

function theme_image_settings_sizes_form(&$form) {
  $header = array(t('Label'), t('Width'), t('Height'));
  foreach (element_children($form) as $key) {
    $row = array();
    $row[] = form_render($form[$key]['label']);
    $row[] = form_render($form[$key]['width']);
    $row[] = form_render($form[$key]['height']);
    $rows[] = $row;

  }
  $output = theme('table', $header, $rows);
  $output .= form_render($form);

  return $output;
}

/**
 * Implementation of hook_menu
 */
function image_menu($may_cache) {
  $items = array();

  if ($may_cache) {
    $items[] = array('path' => 'node/add/image', 'title' => t('image'),
                     'access' => user_access('create images'));
    $items[] = array('path' => 'image', 'title' => t('image galleries'),
                     'access' => user_access('access content'),
                     'type' => MENU_SUGGESTED_ITEM,
                     'callback' => 'image_page');
    $items[] = array('path' => 'image/view', 'title' => t('image'),
                     'access' => user_access('access content'),
                     'type' => MENU_CALLBACK,
                     'callback' => 'image_fetch');
    $items[] = array('path' => 'admin/image', 'title' => t('image galleries'),
                     'access' => user_access('administer images'),
                     'callback' => 'image_admin');
    $items[] = array('path' => 'admin/image/list', 'title' => t('list'),
                     'access' => user_access('administer images'),
                     'type' => MENU_DEFAULT_LOCAL_TASK, 'weight' => -10);
    $items[] = array('path' => 'admin/image/add', 'title' => t('add gallery'),
                     'access' => user_access('administer images'),
                     'type' => MENU_LOCAL_TASK);
  }

  return $items;
}

/**
 * Implements hook_cron. (deletes old temp images)
 */
function image_cron() {
  $path = variable_get('image_default_path', 'images') . '/temp';
  $files = file_scan_directory(file_create_path($path), '.*');
  foreach ($files as $file => $info) {
    if (time() - filemtime($file) > 60*60*6) {
      file_delete($file);
    }
  }
}

/**
 * Implementation of hook_prepare().
 */
function image_prepare(&$node, $field_name) {
  if (is_null($field_name)) {
    $field_name = 'image';
  }
  if ($file = file_check_upload($field_name)) {
    $file = file_save_upload($field_name, _image_filename($file->filename, NULL, TRUE));
    if ($file) {
      if (!image_get_info($file->filepath)) {
        form_set_error($field_name, t('Uploaded file is not a valid image'));
        return;
      }
    }
    else {
      return;
    }
    $node->images['_original'] = $file->filepath;
    _image_build_derivatives($node, true);
    $node->new_file = TRUE;
  }
}

/**
 * implement hook_file_download
 */
function image_file_download($file) {
  $size = image_get_info(file_create_path($file));
  if ($size) {
    $headers = array('Content-Type: ' . $size['mime_type']);
    return $headers;
  }
}

/**
 * Implementation of hook_link.
 */
function image_link($type, $node, $main = 0) {
  $links = array();

  if ($type == "page" && user_access('access content')) {
    if (_image_get_vid()) {
      $links[] = l(t('image galleries'), 'image');
    }
  }

  if ($type == 'node' && $node->type == 'image' && !$main) {
    $sizes = array();
    foreach (_image_get_sizes() as $size) {
      if ($size['label'] && !in_array($size['label'], array('thumbnail', '_original'))) {

        $sizes[] = $size;
      }
    }

    if (count($sizes) > 1) {
      $request = ($_GET['size']) ? $_GET['size'] : 'preview';
      foreach ($sizes as $size) {
        if ($request != $size['label']) {
          $links[] = l($size['label'], 'node/'. $node->nid, NULL, 'size='. urlencode($size['label']));
        }
      }
    }
    if (variable_get('image_view_original', 0)) {
      $links[] = l(t('view original'), 'node/'. $node->nid, NULL, 'size=_original');
    }
  }

  return $links;
}

/**
 * Implementation of hook_block.
 *
 * Offers 2 blocks: latest image and random image
 */
function image_block($op, $delta = 0) {
  switch ($op) {
    case 'list':
      $block[0]['info'] = t('Latest image');
      $block[1]['info'] = t('Random image');

      return $block;
    case 'view':
      if (user_access('access content')) {
        switch($delta) {
          case 0:
            $images = image_get_latest();
            $block['subject'] = t('Latest image');
            $block['content'] = l(image_display($images[0], 'thumbnail'), 'node/'.$images[0]->nid, array(), NULL, NULL, FALSE, TRUE);
            break;
          case 1:
            $images = image_get_random();
            $block['subject'] = t('Random image');
            $block['content'] = l(image_display($images[0], 'thumbnail'), 'node/'.$images[0]->nid, array(), NULL, NULL, FALSE, TRUE);
            break;
        }
      }
      return $block;
  }
}

function image_form_add_thumbnail($form_id, $edit) {
  if ($edit['images']['thumbnail']) {
    $node = (object)($edit);
    $form = array('#type' => 'item', '#title' => t('Thumbnail'), '#value' => image_display($node, 'thumbnail'), '#weight' => -10);
  }
  return $form;
}

/**
 * Implementation of hook_form
 */
function image_form(&$node, &$param) {
  _image_check_settings();

  $form['#attributes'] = array("enctype" => "multipart/form-data");
  $form['title'] = array('#type' => 'textfield', '#title' => t('Title'), '#size' => 60, '#maxlength' => 128, '#required' => TRUE, '#default_value' => $node->title);

  $sizes = _image_get_sizes();
  $form['images']['#tree'] = TRUE;
  if ($node->new_file) {
    $form['images']['_original'] = array('#type' => 'hidden', '#value' => $node->images['_original']);
  }
  else {
    $form['images']['_original'] = array('#type' => 'hidden', '#default_value' => $node->images['_original']);
  }
  foreach ($sizes as $size) {
    if ($node->new_file) {
      $form['images'][$size['label']] = array('#type' => 'hidden', '#value' => $node->images[$size['label']]);
    }
    else {
      $form['images'][$size['label']] = array('#type' => 'hidden', '#default_value' => $node->images[$size['label']]);
    }
  }

  $form['thumbnail']['#after_build'] = 'image_form_add_thumbnail';
  
  $form['image'] = array('#type' => 'file', '#title' => t('Image'), '#description' => t('Click "Browse..." to select an image to upload.'));
  $form['body'] = array('#type' => 'textarea', '#title' => t('Body'), '#default_value' => $node->body);
  $form['format'] = filter_form($node->format);

  return $form;
}

/**
 * Implementation of hook_view
 */
function image_view(&$node, $teaser = 0, $page = 0) {
  if ($page) {
    $terms = taxonomy_node_get_terms_by_vocabulary($node->nid, _image_get_vid());
    $term = array_pop($terms);
    if ($term) {
      $vocabulary = taxonomy_get_vocabulary(_image_get_vid());
      // Breadcrumb navigation
      $breadcrumb = array();
      $breadcrumb[] = array('path' => 'image', 'title' => $vocabulary->name);
      if ($parents = taxonomy_get_parents_all($term->tid)) {
        $parents = array_reverse($parents);
        foreach ($parents as $p) {
          $breadcrumb[] = array('path' => 'image/tid/'. $p->tid, 'title' => $p->name);
        }
      }
      $breadcrumb[] = array('path' => 'node/'. $node->nid);
      menu_set_location($breadcrumb);
    }
  }
  $request = ($_GET['size']) ? $_GET['size'] : 'preview';
  $request = check_plain($request);
  $node = node_prepare($node, $teaser);
  $node->teaser = theme('image_teaser', $node);
  $node->body = theme('image_body', $node, $request);
}

/**
 * Implementation of hook_load
 */
function image_load(&$node) {
  $result = db_query("SELECT filename, filepath FROM {files} WHERE nid=%d", $node->nid);
  $node->images = array();
  while ($file = db_fetch_object($result)) {
    $node->images[$file->filename] = $file->filepath;
  }
  // special images
  if (empty($node->images['thumbnail'])) {
    $node->images['thumbnail'] = $node->images['_original'];
  }
  if (empty($node->images['preview'])) {
    $node->images['preview'] = $node->images['_original'];
  }
}

/**
 * Implementation of hook_insert
 */
function image_insert($node) {
  foreach ($node->images as $label => $image) {
    _image_insert($node, $label, file_create_path($image));
  }
}

/**
 * Implementation of hook_update
 */
function image_update($node) {
  foreach ($node->images as $label => $image) {
    $old_path = db_result(db_query("SELECT filepath FROM {files} WHERE filename='%s' AND nid=%d", $label, $node->nid));
    // This is a new image.
    if ($old_path != $image) {
      file_delete(file_create_path($old_path));
      db_query("DELETE FROM {files} WHERE filename='%s' AND nid=%d", $label, $node->nid);
      _image_insert($node, $label, file_create_path($image));
    }
  }
}

/**
 * Implementation of hook_delete.
 */
function image_delete($node) {
  foreach ($node->images as $label => $image) {
    file_delete(file_create_path($image));
    db_query("DELETE FROM {files} WHERE filename='%s' AND nid=%d", $label, $node->nid);
  }
}

/**
 * Create an <img> tag for an image.
 */
function image_display(&$node, $label = 'preview', $attributes = array()) {
  // regenerate images?
  if ($node->images[$label] != $node->images['_original'] &&
      (!file_exists(file_create_path($node->images[$label])) ||
       filemtime(file_create_path($node->images[$label])) < variable_get('image_updated', 0))) {
    _image_build_derivatives($node);
  }

  if(!$node->images[$label]) {
    return '';
  }

  $info = image_get_info(file_create_path($node->images[$label]));
  $attributes['class'] = "image $label". (isset($attributes['class']) ? " ". $attributes['class'] : "");
  $attr = array('width' => $info['width'], 'height' => $info['height']) + $attributes;
  $output.= theme('image', file_create_url($node->images[$label]), $node->title, $node->title, $attr, FALSE);
  return $output;
}

/**
 * Fetches an image file, allows "shorthand" image urls such of the form:
 * image/view/$nid/$label
 * (e.g. image/view/25/thumbnail or image/view/14)
 */
function image_fetch($nid = 0, $size = 'preview') {
  if ($nid) {
    $node = node_load(array('nid' => $nid));
    if ($node->images[$size]) {
      $file = $node->images[$size];
      $headers = image_file_download($file);
      file_transfer($file, $headers);
    }
  }
}

/**
 * Image gallery callback, displays an image gallery
 */
function image_page($type = NULL, $tid = 0) {
  $galleries = taxonomy_get_tree(_image_get_vid(), $tid, -1, 1);
  for ($i=0; $i < count($galleries); $i++) {
    $galleries[$i]->count = taxonomy_term_count_nodes($galleries[$i]->tid, 'image');
    $tree = taxonomy_get_tree(_image_get_vid(), $galleries[$i]->tid, -1);
    $descendant_tids = array_merge(array($galleries[$i]->tid), array_map('_taxonomy_get_tid_from_term', $tree));
    $last = db_fetch_object(db_query_range(db_rewrite_sql('SELECT n.nid FROM {node} n INNER JOIN {term_node} tn ON n.nid = tn.nid WHERE tn.tid IN (%s) AND n.status = 1 ORDER BY n.sticky DESC, n.created DESC'), implode(',', $descendant_tids), 0, 1));
    $galleries[$i]->latest = node_load(array('nid' => $last->nid));
  }

  $images = array();
  if ($tid) {
    $result = pager_query(db_rewrite_sql("SELECT n.nid FROM {term_node} t INNER JOIN {node} n ON t.nid=n.nid WHERE n.status=1 AND n.type='image' AND t.tid=%d ORDER BY n.sticky DESC, n.created DESC"), variable_get('image_images_per_page', 6), 0, NULL, $tid);
    while ($node = db_fetch_object($result)) {
      $images[] = node_load(array('nid' => $node->nid));
    }

    $gallery = taxonomy_get_term($tid);
    $parents = taxonomy_get_parents($tid);
    foreach ($parents as $parent) {
      $breadcrumb[] = array('path' => 'image/tid/'. $parent->tid, 'title' => $parent->name);
    }
    $breadcrumb[] = array('path' => 'image', 'title' => t('Image galleries'));
    $breadcrumb = array_reverse($breadcrumb);
    drupal_set_title($gallery->name);
  }

  $breadcrumb[] = array('path' => $_GET['q']);
  menu_set_location($breadcrumb);
  $content = theme('image_gallery', $galleries, $images);
  return $content;
}

/**
 * Admin callback for managing galleries
 */
function image_admin() {
  _image_check_settings();

  $op = $_POST['op'];
  $edit = $_POST['edit'];
  
  if (empty($op)) {
    $op = arg(2);
  }
  
  $tid = arg(3);
  if (isset($edit['tid'])) {
    $tid = $edit['tid'];
  }

  switch ($op) {
    case 'add':
      $output = image_admin_gallery();
    case 'edit':
      $output = image_admin_gallery((array)(taxonomy_get_term($tid)));
      break;
    case t('Delete'):
      if (!$edit['confirm']) {
        $term = taxonomy_get_term($tid);

        $form['tid'] = array('#type' => 'hidden', '#value' => $tid);

        return confirm_form('image_confirm_delete', $form, t('Are you sure you want to delete the gallery %name?', array('%name' => theme('placeholder', $term->name))),
                            'admin/image', t('Deleting a gallery will delete all sub-forums as well. However, the images will not be deleted. This action cannot be undone.'), t('Delete'), t('Cancel'));

        break;
      }
      else {
        $name = $edit['name'];
        $edit['name'] = 0;
      }
    case t('Submit'):
      $status = taxonomy_save_term($edit);
      switch ($status) {
        case SAVED_NEW:
          drupal_set_message(t('Created new gallery %term.', array('%term' => theme('placeholder', $edit['name']))));
          break;
        case SAVED_UPDATED:
          drupal_set_message(t('The gallery %term has been updated.', array('%term' => theme('placeholder', $edit['name']))));
          break;
        case SAVED_DELETED:
          drupal_set_message(t('The gallery %term has been deleted.', array('%term' => theme('placeholder', $name))));
          break;
      }
      drupal_goto('admin/image');
    default:
      $output = image_admin_overview();
  }
  return $output;
}

function image_admin_overview() {
  $header = array(t('Name'), t('Operations'));

  $tree = taxonomy_get_tree(_image_get_vid());
  if ($tree) {
    foreach ($tree as $term) {
      $rows[] = array(_image_depth($term->depth) .' '. $term->name, l(t('edit gallery'), "admin/image/edit/$term->tid"));
    }
    return theme('table', $header, $rows);
  }
  else {
    return t('No galleries available');
  }
}

function image_admin_gallery($edit = array()) {
  if (empty($edit)) {
    $edit['vid'] = _image_get_vid();
  }

  $form['name'] = array('#type' => 'textfield', '#title' => t('Gallery name'), '#default_value' => $edit['name'], '#size' => 60, '#maxlength' =>  64, '#description' => t('The name is used to identify the gallery.'));
  $form['description'] = array('#type' => 'textarea', '#title' => t('Description'), '#default_value' => $edit['description'], '#cols' => 60, '#rows' => 5, '#description' => ('The description can be used to provide more information about the image gallery.'));
  $form['parent']['#tree'] = TRUE;
  $form['parent'][0] = _image_parent_select($edit['tid'], t('Parent'), 'forum');
  $form['weight'] = array('#type' => 'weight', '#title' => t('Weight'), '#default_value' => $edit['weight'], '#delta' => 10, '#description' => t('When listing galleries, those with with light (small) weights get listed before containers with heavier (larger) weights. Galleries with equal weights are sorted alphabetically.'));
  
  $form['vid'] = array('#type' => 'hidden', '#value' => _image_get_vid());
  $form['submit' ] = array('#type' => 'submit', '#value' => t('Submit'));
  if ($edit['tid']) {
    $form['delete'] = array('#type' => 'submit', '#value' => t('Delete'));
    $form['tid'] = array('#type' => 'hidden', '#value' => $edit['tid']);
  }

  return drupal_get_form('image_admin_gallery', $form);
}


function _image_parent_select($tid, $title) {
  $parents = taxonomy_get_parents($tid);
  if ($parents) {
    $parent = array_shift($parents);
    $parent = $parent->tid;
  }
  else {
    $parent = 0;
  }

  $children = taxonomy_get_tree(_image_get_vid(), $tid);

  // A term can't be the child of itself, nor of its children.
  foreach ($children as $child) {
    $exclude[] = $child->tid;
  }
  $exclude[] = $tid;

  $tree = taxonomy_get_tree(_image_get_vid());
  $options[0] = '<'. t('root') .'>';
  if ($tree) {
    foreach ($tree as $term) {
      if (!in_array($term->tid, $exclude)) {
        $options[$term->tid] = _image_depth($term->depth) .' '. $term->name;
      }
    }
  }

  $description = t('Image galleries may be nested below other galleries.');

  return array('#type' => 'select', '#title' => $title, '#default_value' => $parent, '#options' => $options, '#description' => $description, '#required' => TRUE);
}

/**
 * Theme a teaser
 */
function theme_image_teaser($node) {
 return l(image_display($node, 'thumbnail'), 'node/'. $node->nid, array(), NULL, NULL, FALSE, TRUE) . $node->teaser;
}

/**
 * Theme a body
 */
function theme_image_body($node, $size) {
 return image_display($node, $size) . $node->body;
}

/**
 * Theme a gallery page
 */
function theme_image_gallery($galleries, $images) {
  drupal_set_html_head(theme('stylesheet_import', base_path() . drupal_get_path('module', 'image') .'/image.css'));

  // We'll add height to keep thumbnails lined up.
  $size = _image_get_dimensions('thumbnail');
  $width = $size['width'];
  $height = $size['height'];

  $content = '';
  if (count($galleries)) {
    $content.= '<ul class="galleries">';
    foreach ($galleries as $gallery) {
      $content .= '<li style="height : '.$height .'px">';
      if ($gallery->count)
        $content.= l(image_display($gallery->latest, 'thumbnail'), 'image/tid/'.$gallery->tid, array(), NULL, NULL, FALSE, TRUE);
      $content.= "<h3>".l($gallery->name, 'image/tid/'.$gallery->tid) . "</h3>\n";
      $content.= '<div class="description">'. check_markup($gallery->description) ."</div>\n";
      $content.= '<p class="count">' . format_plural($gallery->count, 'There is 1 image in this gallery', 'There are %count images in this gallery') . "</p>\n";
      if ($gallery->latest->changed) {
        $content.= '<p class="last">'. t('Last updated: %date', array('%date' => format_date($gallery->latest->changed))) . "</p>\n";
      }
      $content.= "</li>\n";
    }
    $content.= "</ul>\n";
  }

  if (count($images)) {
    $height += 75;
    $content.= '<ul class="images">';
    foreach ($images as $image) {
      $content .= '<li';
      if ($image->sticky) {
        $content .= ' class="sticky"';
      }
      $content .= ' style="height : '.$height .'px; width : '.$width.'px;"';
      $content .= ">\n";
      $content .= l(image_display($image, 'thumbnail'), 'node/'.$image->nid, array(), NULL, NULL, FALSE, TRUE);
      $content .= '<h3>'.l($image->title, 'node/'.$image->nid)."</h3>";
      if (theme_get_setting('toggle_node_info_' . $image->type)) {
        $content .= '<div class="author">'. t('Posted by: %name', array('%name' => theme('username', $image))) . "</div>\n";
        if ($image->created > 0) {
          $content .= '<div class="date">'.format_date($image->created)."</div>\n";
        }
      }
      $content .= "</li>\n";
    }
    $content.= "</ul>\n";
  }

  if ($pager = theme('pager', NULL, variable_get('image_images_per_page', 6), 0)) {
    $content.= $pager;
  }

  If (count($images) + count($galleries) == 0) {
      $content.= '<p class="count">' . format_plural(0, 'There is 1 image in this gallery', 'There are %count images in this gallery') . "</p>\n";
  }

  return $content;
}

/**
 * Fetch a random N image(s) - optionally from a given term.
 */
function image_get_random($count = 1, $tid = 0) {
  if ($tid != 0) {
    $result = db_query_range(db_rewrite_sql("SELECT n.nid FROM {term_node} tn LEFT JOIN {node} n ON n.nid=tn.nid WHERE n.type='image' AND n.status=1 AND tn.tid=%d ORDER BY RAND()"), $tid, 0, $count);
  }
  else {
    $result = db_query_range(db_rewrite_sql("SELECT n.nid FROM {node} n WHERE n.type='image' AND n.status=1 ORDER BY RAND()"), 0, $count);
  }
  $output = array();
  while ($nid = db_fetch_object($result)) {
    $output[] = node_load(array('nid' => $nid->nid));
  }
  return $output;
}

/**
 * Fetch the latest N image(s) - optionally from a given term.
 */
function image_get_latest($count = 1, $tid = 0) {
  if ($tid != 0) {
    $result = db_query_range(db_rewrite_sql("SELECT n.nid FROM {term_node} tn LEFT JOIN {node} n ON n.nid=tn.nid WHERE n.type='image' AND n.status=1 AND tn.tid=%d ORDER BY n.changed DESC"), $tid, 0, $count);
  }
  else {
    $result = db_query_range(db_rewrite_sql("SELECT n.nid FROM {node} n WHERE n.type='image' AND n.status=1 ORDER BY changed DESC"), 0, $count);
  }
  $output = array();
  while ($nid = db_fetch_object($result)) {
    $output[] = node_load(array('nid' => $nid->nid));
  }
  return $output;
}

/**
 * Verify the image module and toolkit settings.
 */
function _image_check_settings() {
  // File paths
  $image_path = file_create_path(variable_get('image_default_path', 'images'));
  $temp_path = rtrim($image_path, '/') . '/temp';

  if (!file_check_directory($image_path, FILE_CREATE_DIRECTORY, 'image_default_path')) {
    return false;
  }
  if (!file_check_directory($temp_path, FILE_CREATE_DIRECTORY, 'image_default_path')) {
    return false;
  }

  // Sanity check : make sure we've got a working toolkit
  if (!image_get_toolkit()) {
    drupal_set_message(t('Make sure you have a working image toolkit installed and enabled, for more information see: %settings', array('%settings' => l(t('the settings page'), 'admin/settings'))), 'error');
    return false;
  }
  return true;
}

/**
 * Generate image derivatives.
 */
function _image_build_derivatives(&$node, $temp = FALSE) {
  // sanity check:
  if (!_image_check_settings()) {
    return false;
  }
  $info = image_get_info(file_create_path($node->images['_original']));
  $sizes = _image_get_sizes();
  if (!$temp) {
    _image_remove($node);
  }
  foreach ($sizes as $size) {
    if ($size['label'] && $size['width'] && $size['height']) {
      if ($info['width'] > $size['width'] || $info['height'] > $size['height']) {
        $source = file_create_path($node->images['_original']);
        $destination = _image_filename(basename($source), $size['label'], $temp);
        if (!image_scale($source, file_create_path($destination), $size['width'], $size['height'])) {
          drupal_set_message(t('Unable to create %label image', array('%label' => $size['label'])), 'error');
        }
        else {
          $node->images[$size['label']] = $destination;
          if (!$temp) {
            _image_insert($node, $size['label'], file_create_path($destination));
          }
        }
      }
      else {
        $node->images[$size['label']] = $node->images['_original'];
      }
    }
  }
}

function _image_remove($node) {
  $result = db_query("SELECT * FROM {files} WHERE nid=%d AND filename!='_original'", $node->nid);
  while ($file = db_fetch_object($result)) {
    // Never delete the original!
    if ($file->filepath != $node->images['_original']) {
      file_delete(file_create_path($file->filepath));
    }
  }
  db_query("DELETE FROM {files} WHERE nid=%d AND filename!='_original'", $node->nid);
}

/**
 * Creates an image filename.
 */
function _image_filename($filename, $type = NULL, $temp = FALSE) {
  $path = variable_get('image_default_path', 'images') .'/';
  if ($temp) {
    $path .= 'temp/';
  }
  
  if ($type) {
    $pos = strrpos($filename, '.');
    if ($pos === false) {
      // The file had no extension - which happens in really old image.module
      // versions, so figure out the extension.
      $info = image_get_info(file_create_path($path . $filename));
      $filename = $filename .'.'. $type .'.'. $info['extension'];
    }
    else {
      $filename = substr($filename, 0, $pos) .'.'. $type . substr($filename, $pos);
    }
  }

  return $path . $filename;
}

/**
 * Helper function to return the defined sizes (or proper defaults).
 */
function _image_get_sizes() {
  $sizes = variable_get('image_sizes', array(array('width' => 100, 'height' => 100, 'label' => 'thumbnail'),
                                             array('width' => 640, 'height' => 640, 'label' => 'preview')));
  return array_filter($sizes, create_function('$size', 'return !empty($size["label"]);'));
}

function _image_required_sizes() {
  return array('thumbnail', 'preview', '_original');
}

function _image_get_dimensions($label) {
  foreach (_image_get_sizes() as $size) {
    if ($size['label'] == $label) {
      return $size;
    }
  }
  return array();
}

/**
 * Moves temporary (working) images to the final directory and stores
 * relevant information in the files table
 */
function _image_insert($node, $label, $image) {
  $dest = _image_filename(basename($image));
  if (file_copy($image, $dest)) {
    $info = image_get_info(file_create_path($dest));
    $file->filename = $label;
    $file->filepath = _image_filename(basename($image));
    $file->filemime = $info['mime_type'];
    $file->filesize = filesize(file_create_path($dest));
    $fid = db_next_id('{files}_fid');
    db_query("INSERT INTO {files} (fid, nid, filename, filepath, filemime, filesize) VALUES (%d, %d, '%s', '%s', '%s', '%s')",
             $fid, $node->nid, $file->filename, $file->filepath, $file->filemime, $file->filesize);
    db_query("INSERT INTO {file_revisions} (fid, vid, description, list) VALUES (%d, %d, '%s', %d)",
             $fid, $node->vid, '', 0);
  }
}

/**
 * Helper function used to generate indentation for gallery list
 *
 * @param $depth Depth of the indentation
 * @param $graphic HTML text to be repeated for each stage of depth
 */
function _image_depth($depth, $graphic = '--') {
  for ($n = 0; $n < $depth; $n++) {
    $result .= $graphic;
  }
  return $result;
}

/**
 * Returns (and possibly creates) a new vocabulary for Image galleries.
 */
function _image_get_vid() {
  $vid = variable_get('image_nav_vocabulary', '');
  if (empty($vid)) {
    // Check to see if an image gallery vocabulary exists
    $vid = db_result(db_query("SELECT vid FROM {vocabulary} WHERE module='%s'", 'image'));
    if (!$vid) {
      $vocabulary = array('name' => t('Image Galleries'), 'multiple' => '0', 'required' => '0', 'hierarchy' => '1', 'relations' => '0', 'module' => 'image', 'nodes' => array('image' => 1));
      taxonomy_save_vocabulary($vocabulary);
      $vid = $vocabulary['vid'];
    }
    variable_set('image_nav_vocabulary', $vid);
  }

  return $vid;
}

?>