<?php
// $Id$

function image_gallery_install() {
  //Nothing to do.
}

function image_gallery_update_1() {
  $ret = array();
  if ($vid = variable_get('image_nav_vocabulary', '')) {
    $ret[] = update_sql("UPDATE {vocabulary} SET module='image_gallery' WHERE vid=". (int) $vid);
  }
  else {
    $ret[] = update_sql("UPDATE {vocabulary} SET module='image_gallery' WHERE module='image'");
  }
  return $ret;
}
